name: controlled-fixpoint-v1
version: 0.1.0.0
github: "rybla/controlled-fixpoint-v1"
license: BSD-3-Clause
author: "Henry Blanchette"
maintainer: "henry@rybl.net"
copyright: "MIT"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            experiment

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:
  Please see the README on GitHub at
  <https://github.com/rybla/controlled-fixpoint-v1#readme>

default-extensions:
  - LambdaCase
  - BlockArguments
  - GADTs
  - OverloadedRecordDot
  - DuplicateRecordFields

dependencies:
  - base >= 4.7 && < 5
  - mtl
  - transformers
  - array
  - text
  - containers
  - parallel
  - list-t
  - pretty
  - newtype-generics
  - lens
  - listsafe
  - singletons # probably can remove this
  - singletons-th # probably can remove this

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  controlled-fixpoint-v1-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - controlled-fixpoint-v1
      - filepath
      - parseargs

tests:
  controlled-fixpoint-v1-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - controlled-fixpoint-v1
      - filepath
      - tasty
      - tasty-hunit
      - tasty-golden
